### PR TITLE
Add column latest cd4 count and latest CD4 date in arctive on ART report

### PR DESCRIPTION
**Pull request by gabriel090**

### CODE REVIEW

**Comment by gabriel** [comment]
I think you meant @gabriel090  :)

**Comment by njorocs** [comment]
> I think you meant @gabriel090 :)

Sure. My apologies.

**Comment by gabriel090** [comment]
> Include screenshot for changes done as its an excel and cannot be reviewed

I have attached it

**Review by njorocs — APPROVED** [review]
lgtm

**Review by patryllus — APPROVED** [review]
lgtm

**Pull request merged**
