### PR TITLE
add form metadata for MAT

### PR DESCRIPTION
**Pull request by ojwanganto**
Adding form metadata for MAT program

### CODE REVIEW

**Comment by ojwanganto** [comment]
@donaldkibet @makombe - could you kindly counter-check the form uuids before I can proceed? I have noted two similar forms: MAT intake and followup and MAT followup forms. It is not clear whether one is part of another or they should just remain two. I will followup with BA tomorrow.

**Comment by makombe** [comment]
> @donaldkibet @makombe - could you kindly counter-check the form uuids before I can proceed? I have noted two similar forms: MAT intake and followup and MAT followup forms. It is not clear whether one is part of another or they should just remain two. I will followup with BA tomorrow.

Ideally we should have unique form uuids, ony encounter uuid/name can be shared across forms.

**Comment by ojwanganto** [comment]
@makombe - we transitioned to an approach where every form defines it's encounter type. That is what is common in the community

**Review by makombe — APPROVED** [review]
LGTM

**Pull request merged**
