### PR TITLE
Added Age at reporting in Active on ART linelist - definition and evaluator

### PR DESCRIPTION
**Pull request by patryllus**
age_at_reporting

### CODE REVIEW

**Review by njorocs — APPROVED** [review]

**Review by njorocs — APPROVED** [review]

**Review by njorocs — APPROVED** [review]

**Review by njorocs — APPROVED** [review]

**Review by njorocs — APPROVED** [review]

**Review by njorocs — APPROVED** [review]

**Review by njorocs — APPROVED** [review]

**Comment by ojwanganto** [comment]
I don't understand the changes not related to age at reporting. Can we clean this up?

**Review by njorocs — COMMENTED** [review]
Stability should be fetched from etl_patient_hiv_followup. This has been corrected in commit #[67619a1](https://github.com/palladiumkenya/openmrs-module-kenyaemr/pull/935/commits/67619a15ab936410d15e03ee15afe07db71b1e52)

**Review by ojwanganto — COMMENTED** [review]
@njorocs added a definition for Age at reporting which we can reuse.

**Comment by patryllus** [comment]
@ojwanganto  they are all related to one report  - Active on ART linelist. These are columns for Active on ART Line list - approved by @njorocs  and @makombe at various stages

**Comment by patryllus** [comment]
@ojwanganto but not yet merged.

**Pull request closed without merging**
