### PR TITLE
In the MCH Antenatal Visit form, make Height and Weight in the vitals…

### PR DESCRIPTION
**Pull request by gabriel090**
In the MCH Antenatal Visit form, make Height and Weight in the vitals section mandatory.

### CODE REVIEW

**Review by patryllus — CHANGES_REQUESTED** [review]
Use express validations in beforeSubmit function instead of required=true
 eg   if (patientHeight == false &amp;&amp; personPresent == SELF) {
                jq('#greencard').smartWizard('setError', {stepnum: 1, iserror: true});
                getField('height.error').html('Please specify patient height').show();
                return false;
            }else{
                getField('height.error').html('Please specify patient height').hide();
            }

**Comment by gabriel090** [comment]
> Use express validations in beforeSubmit function instead of required=true eg if (patientHeight == false && personPresent == SELF) { jq('#greencard').smartWizard('setError', {stepnum: 1, iserror: true}); getField('height.error').html('Please specify patient height').show(); return false; }else{ getField('height.error').html('Please specify patient height').hide(); }

Applied changes. Thaks

**Review by patryllus — CHANGES_REQUESTED** [review]
format
Kindly format this properly

**Review by patryllus — APPROVED** [review]
Looks okay

**Pull request merged**
